name: dvg
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.0
  - matplotlib=3.4.2
  - pytorch=1.2.0
  - rasterio
  - scikit-learn=0.23.2
  - scipy=1.1.0
  - torchvision=0.4.0
  - xarray=0.17.0
  - pip:
    - future==0.18.2
    - gpytorch==0.3.0
    - ipython==7.24.1
    - progressbar==2.5
    - tensorboard==2.5.0

